name: 'Semantic Release'
description: 'Reusable composite action for semantic-release with changelog generation and PR previews'

inputs:
  mode:
    description: 'Operation mode: "release" or "pr-changelog"'
    required: true
    default: 'release'
  github-token:
    description: 'GitHub token with contents:write and pull-requests:write permissions'
    required: true
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  extra-plugins:
    description: 'Space-separated list of additional semantic-release plugins to install'
    required: false
    default: ''
  dry-run:
    description: 'Run in dry-run mode (no release created, only in release mode)'
    required: false
    default: 'false'

outputs:
  new-release-published:
    description: 'Whether a new release was published'
    value: ${{ steps.release.outputs.new-release-published }}
  new-release-version:
    description: 'The new release version'
    value: ${{ steps.release.outputs.new-release-version }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Install semantic-release and plugins
      shell: bash
      run: |
        npm install --no-save \
          semantic-release@24 \
          @semantic-release/changelog@6 \
          @semantic-release/git@10 \
          conventional-changelog-conventionalcommits@8 \
          ${{ inputs.extra-plugins }}

    - name: Generate default config if none exists
      shell: bash
      run: |
        if [ ! -f .releaserc.yml ] && [ ! -f .releaserc.yaml ] && [ ! -f .releaserc.json ] && [ ! -f .releaserc.js ] && [ ! -f .releaserc.cjs ] && [ ! -f release.config.js ] && [ ! -f release.config.cjs ]; then
          cat > .releaserc.yml << 'RCEOF'
        branches:
          - main
        plugins:
          - - "@semantic-release/commit-analyzer"
            - preset: conventionalcommits
          - - "@semantic-release/release-notes-generator"
            - preset: conventionalcommits
          - - "@semantic-release/changelog"
            - changelogFile: CHANGELOG.md
          - - "@semantic-release/git"
            - assets:
                - CHANGELOG.md
                - package.json
                - package-lock.json
              message: "chore(release): ${nextRelease.version} [skip ci]"
          - "@semantic-release/github"
        RCEOF
          echo "::notice::Created default .releaserc.yml (no config found in repo)"
        else
          echo "::notice::Using existing release config from repository"
        fi

    - name: Run semantic-release
      if: inputs.mode == 'release'
      id: release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        ARGS=""
        if [ "${{ inputs.dry-run }}" = "true" ]; then
          ARGS="--dry-run"
        fi

        npx semantic-release $ARGS 2>&1 | tee /tmp/semantic-release-output.log

        # Parse output for version
        VERSION=$(grep -oP 'Published release \K[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.]+)?' /tmp/semantic-release-output.log || echo "")
        if [ -n "$VERSION" ]; then
          echo "new-release-published=true" >> "$GITHUB_OUTPUT"
          echo "new-release-version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "::notice::Released version $VERSION"
        else
          echo "new-release-published=false" >> "$GITHUB_OUTPUT"
          echo "new-release-version=" >> "$GITHUB_OUTPUT"
          echo "::notice::No new release published"
        fi

    - name: Generate PR changelog preview
      if: inputs.mode == 'pr-changelog'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        # Run semantic-release dry-run to generate release notes
        npx semantic-release --dry-run 2>&1 | tee /tmp/semantic-release-output.log || true

        # Extract release notes - semantic-release prints them between specific markers
        # Try multiple extraction strategies
        NOTES=""

        # Strategy 1: Extract the release notes section from dry-run output
        NOTES=$(awk '/^#{1,3} \[?[0-9]+\.[0-9]+\.[0-9]+/,0' /tmp/semantic-release-output.log 2>/dev/null || echo "")

        # Strategy 2: Look for "Release note" text
        if [ -z "$NOTES" ]; then
          NOTES=$(sed -n '/Release note/,/^$/p' /tmp/semantic-release-output.log 2>/dev/null | tail -n +2 || echo "")
        fi

        # Strategy 3: Extract lines with conventional commit info
        if [ -z "$NOTES" ]; then
          FEATURES=$(grep -c "feat:" /tmp/semantic-release-output.log 2>/dev/null || echo "0")
          FIXES=$(grep -c "fix:" /tmp/semantic-release-output.log 2>/dev/null || echo "0")
          if [ "$FEATURES" != "0" ] || [ "$FIXES" != "0" ]; then
            NOTES="Detected changes: $FEATURES feature(s), $FIXES fix(es)"
          fi
        fi

        if [ -z "$NOTES" ]; then
          NOTES="No releasable changes detected based on conventional commits."
        fi

        echo "$NOTES" > /tmp/pr-changelog.md
        echo "::notice::Generated PR changelog preview"

    - name: Update PR body with changelog
      if: inputs.mode == 'pr-changelog'
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        bash "${{ github.action_path }}/scripts/update-pr-changelog.sh"
