#!/usr/bin/env bash
set -euo pipefail

# Update PR body with changelog preview between HTML comment markers.
# Delegates to update-pr-section.sh.
#
# Requires: GH_TOKEN, PR_NUMBER, /tmp/pr-changelog.md

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

if [ ! -f /tmp/pr-changelog.md ]; then
  echo "::warning::No changelog file found at /tmp/pr-changelog.md"
  exit 0
fi

# Build the section content with heading, blockquote, and footer
CHANGELOG_BLOCKQUOTE=$(sed 's/^/> /' /tmp/pr-changelog.md)

cat > /tmp/pr-changelog-section.md << SECTION_EOF
## Release Preview

This pull request will generate the following changelog entries when merged:

${CHANGELOG_BLOCKQUOTE}

---
*This section was automatically generated by [semantic-release-action](https://github.com/Rajlus/semantic-release-action).*
SECTION_EOF

exec "$SCRIPT_DIR/update-pr-section.sh" \
  "<!-- CHANGELOG_START -->" \
  "<!-- CHANGELOG_END -->" \
  "/tmp/pr-changelog-section.md" \
  "changelog preview"
