#!/usr/bin/env bash
set -euo pipefail

# Update PR body with code review between HTML comment markers.
# Delegates to update-pr-section.sh.
#
# Requires: GH_TOKEN, PR_NUMBER, /tmp/code-review.md

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

if [ ! -f /tmp/code-review.md ]; then
  echo "::warning::No review file found at /tmp/code-review.md"
  exit 0
fi

# Build the section content with heading and footer
cat > /tmp/code-review-section.md << SECTION_EOF
## 🤖 Code Review

$(cat /tmp/code-review.md)

---
*This section was automatically generated by [Claude Code Review](https://github.com/Rajlus/semantic-release-action).*
SECTION_EOF

exec "$SCRIPT_DIR/update-pr-section.sh" \
  "<!-- CODE_REVIEW_START -->" \
  "<!-- CODE_REVIEW_END -->" \
  "/tmp/code-review-section.md" \
  "code review"
