#!/usr/bin/env bash
set -euo pipefail

# Update PR body with changelog preview between HTML comment markers.
# Adapted from Azure DevOps add-pr-changelog.sh for GitHub Actions.
#
# Requires: GITHUB_TOKEN, PR_NUMBER, /tmp/pr-changelog.md

START_MARKER="<!-- CHANGELOG_START -->"
END_MARKER="<!-- CHANGELOG_END -->"

if [ -z "${PR_NUMBER:-}" ]; then
  echo "::warning::PR_NUMBER not set, skipping PR body update"
  exit 0
fi

if [ ! -f /tmp/pr-changelog.md ]; then
  echo "::warning::No changelog file found at /tmp/pr-changelog.md"
  exit 0
fi

CHANGELOG_CONTENT=$(cat /tmp/pr-changelog.md)

# Build the changelog section (blockquote format like Azure original)
CHANGELOG_BLOCKQUOTE=$(echo "$CHANGELOG_CONTENT" | sed 's/^/> /')

CHANGELOG_SECTION="${START_MARKER}
## Release Preview

This pull request will generate the following changelog entries when merged:

${CHANGELOG_BLOCKQUOTE}

---
*This section was automatically generated by [semantic-release-action](https://github.com/Rajlus/semantic-release-action).*
${END_MARKER}"

# Get current PR body
CURRENT_BODY=$(gh pr view "$PR_NUMBER" --json body --jq '.body' 2>/dev/null || echo "")

if echo "$CURRENT_BODY" | grep -qF "$START_MARKER"; then
  echo "::notice::Updating existing changelog section in PR description"
  # Extract parts before and after the changelog section
  BEFORE=$(echo "$CURRENT_BODY" | awk "/$START_MARKER/{exit} {print}")
  AFTER=$(echo "$CURRENT_BODY" | awk "found{print} /$END_MARKER/{found=1}")
  NEW_BODY="${BEFORE}${CHANGELOG_SECTION}
${AFTER}"
else
  echo "::notice::Appending changelog section to PR description"
  if [ -n "$CURRENT_BODY" ]; then
    NEW_BODY="${CURRENT_BODY}

${CHANGELOG_SECTION}"
  else
    NEW_BODY="${CHANGELOG_SECTION}"
  fi
fi

# Update PR body via temp file (avoids argument length limits)
TMPFILE=$(mktemp)
echo "$NEW_BODY" > "$TMPFILE"
gh pr edit "$PR_NUMBER" --body-file "$TMPFILE"
rm -f "$TMPFILE"

echo "::notice::PR #$PR_NUMBER body updated with changelog preview"
