#!/usr/bin/env bash
set -euo pipefail

# Update PR body with changelog preview between HTML comment markers.
# Requires: GITHUB_TOKEN, PR_NUMBER, /tmp/pr-changelog.md

START_MARKER="<!-- semantic-release-changelog-start -->"
END_MARKER="<!-- semantic-release-changelog-end -->"

if [ -z "${PR_NUMBER:-}" ]; then
  echo "::warning::PR_NUMBER not set, skipping PR body update"
  exit 0
fi

if [ ! -f /tmp/pr-changelog.md ]; then
  echo "::warning::No changelog file found at /tmp/pr-changelog.md"
  exit 0
fi

CHANGELOG=$(cat /tmp/pr-changelog.md)

CHANGELOG_SECTION="${START_MARKER}
---

<details>
<summary><strong>Preview: Release Changelog</strong></summary>

${CHANGELOG}

</details>

*Auto-generated by [semantic-release-action](https://github.com/Rajlus/semantic-release-action)*
${END_MARKER}"

# Get current PR body
CURRENT_BODY=$(gh pr view "$PR_NUMBER" --json body --jq '.body' 2>/dev/null || echo "")

if echo "$CURRENT_BODY" | grep -qF "$START_MARKER"; then
  # Replace existing changelog section using a temp file approach
  # (awk with multi-line replacement is fragile, use Python if available, else sed)
  BEFORE=$(echo "$CURRENT_BODY" | awk "/$START_MARKER/{exit} {print}")
  AFTER=$(echo "$CURRENT_BODY" | awk "found{print} /$END_MARKER/{found=1}")

  NEW_BODY="${BEFORE}${CHANGELOG_SECTION}
${AFTER}"
else
  # Append changelog section
  NEW_BODY="${CURRENT_BODY}

${CHANGELOG_SECTION}"
fi

# Update PR body (use temp file to avoid argument length limits)
TMPFILE=$(mktemp)
echo "$NEW_BODY" > "$TMPFILE"
gh pr edit "$PR_NUMBER" --body-file "$TMPFILE"
rm -f "$TMPFILE"

echo "::notice::PR #$PR_NUMBER body updated with changelog preview"
